# Translations template for nova.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 13.0.0.0b2.dev521\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-01-08 06:11+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: nova/filters.py:99
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr ""

#: nova/filters.py:125
#, python-format
msgid ""
"Filtering removed all hosts for the request with instance ID "
"'%(inst_uuid)s'. Filter results: %(str_results)s"
msgstr ""

#: nova/service.py:151
#, python-format
msgid ""
"Updating service version for %(binary)s on %(host)s from %(old)i to "
"%(new)i"
msgstr ""

#: nova/service.py:191
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr ""

#: nova/utils.py:326
#, python-format
msgid "Executing RootwrapDaemonHelper.execute cmd=[%(cmd)r] kwargs=[%(kwargs)r]"
msgstr ""

#: nova/wsgi.py:155
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:259
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:279
msgid "WSGI server has stopped."
msgstr ""

#: nova/api/ec2/__init__.py:466
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: nova/api/ec2/cloud.py:419
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:462
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:474
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:487
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:790
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:863
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:867
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:166
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:907
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: nova/api/ec2/cloud.py:937
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:396
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:1304
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:1309
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1314
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1347
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1500
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:1615
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1651
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1720
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/ec2utils.py:292
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/openstack/__init__.py:111
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:340
msgid "V2.1 API has been disabled by configuration"
msgstr ""

#: nova/api/openstack/__init__.py:393
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:537
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:540
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/compute/assisted_volume_snapshots.py:56
#: nova/api/openstack/compute/legacy_v2/contrib/assisted_volume_snapshots.py:53
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/assisted_volume_snapshots.py:72
#: nova/api/openstack/compute/legacy_v2/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:505
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/hosts.py:141
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:163
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/hosts.py:162
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:186
#, python-format
msgid "Enabling host %s."
msgstr ""

#: nova/api/openstack/compute/hosts.py:164
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:188
#, python-format
msgid "Disabling host %s."
msgstr ""

#: nova/api/openstack/compute/server_external_events.py:87
#: nova/api/openstack/compute/legacy_v2/contrib/server_external_events.py:103
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:154
#, python-format
msgid "Detach interface %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:77
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:111
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:299
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:543
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/cells/messaging.py:1113
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, "
"updated_since=%(since_str)s"
msgstr ""

#: nova/cells/scheduler.py:239
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s "
"second(s)"
msgstr ""

#: nova/cells/filters/target_cell.py:59
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler "
"hint"
msgstr ""

#: nova/compute/api.py:1531
msgid "instance termination disabled"
msgstr ""

#: nova/compute/api.py:1544
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1614
msgid "Instance is already in deleting state, ignoring this request"
msgstr ""

#: nova/compute/api.py:1659
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: "
"%(status)s"
msgstr ""

#: nova/compute/api.py:1669
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1686
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1726
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/api.py:2135
msgid "It's not supported to backup volume backed instance."
msgstr ""

#: nova/compute/api.py:2273
#, python-format
msgid "Skipping quiescing instance: %(reason)s."
msgstr ""

#: nova/compute/api.py:3829
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:3934
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/claims.py:143
#, python-format
msgid ""
"Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB, vcpus "
"%(vcpus)d CPU"
msgstr ""

#: nova/compute/claims.py:159
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:237
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:244
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:251
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""

#: nova/compute/manager.py:336
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:730 nova/conductor/manager.py:155
#: nova/console/manager.py:68 nova/consoleauth/manager.py:60
msgid "Reloading compute RPC API"
msgstr ""

#: nova/compute/manager.py:843
msgid "Deleting instance as it has been evacuated from this host"
msgstr ""

#: nova/compute/manager.py:855
msgid "Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""

#: nova/compute/manager.py:1031
msgid ""
"Service started deleting the instance during the previous run, but did "
"not finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1165
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""

#: nova/compute/manager.py:1187
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:1237
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:1302
msgid ""
"Instance lifecycle events from the compute driver have been disabled. "
"Note that lifecycle changes to an instance outside of the compute service"
" will only be synchronized by the _sync_power_states periodic task."
msgstr ""

#: nova/compute/manager.py:1819
#, python-format
msgid "Took %0.2f seconds to deallocate network for instance."
msgstr ""

#: nova/compute/manager.py:1917
#, python-format
msgid "Took %0.2f seconds to build instance."
msgstr ""

#: nova/compute/manager.py:2030
#, python-format
msgid "Took %0.2f seconds to spawn the instance on the hypervisor."
msgstr ""

#: nova/compute/manager.py:2275
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:2299
#, python-format
msgid "Took %0.2f seconds to destroy the instance on the hypervisor."
msgstr ""

#: nova/compute/manager.py:2341
#, python-format
msgid "Took %(time).2f seconds to detach %(num)s volumes for instance."
msgstr ""

#: nova/compute/manager.py:2470
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2514
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""

#: nova/compute/manager.py:2736
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:2833
msgid "disk on shared storage, recreating using existing disk"
msgstr ""

#: nova/compute/manager.py:2837
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:2917
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:2948
#, python-format
msgid "Detaching from volume api: %s"
msgstr ""

#: nova/compute/manager.py:2975
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:3111
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:3245
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:3293
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3328
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:3377
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:3431
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3452
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3649
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:3699
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:4053
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:4069
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:4106 nova/compute/manager.py:4123
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:4162
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:4401
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:4669
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:4694
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:4879
#, python-format
msgid "Swapping volume %(old_volume)s for %(new_volume)s"
msgstr ""

#: nova/compute/manager.py:5260
msgid "_post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:5342
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5344
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:5382
msgid "Post operation of migration started"
msgstr ""

#: nova/compute/manager.py:5671
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/compute/manager.py:5686
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:5740
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5791
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""

#: nova/compute/manager.py:5838
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:5860
msgid "Bandwidth usage not supported by hypervisor."
msgstr ""

#: nova/compute/manager.py:6023 nova/compute/manager.py:6080
#, python-format
msgid "During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""

#: nova/compute/manager.py:6067
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to"
" host %(dst)s"
msgstr ""

#: nova/compute/manager.py:6088
#, python-format
msgid ""
"During _sync_instance_power_state the DB power_state (%(db_power_state)s)"
" does not match the vm_power_state from the hypervisor "
"(%(vm_power_state)s). Updating power_state in the DB to match the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:6235
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:6268
#, python-format
msgid "Compute node '%s' not found in update_available_resource."
msgstr ""

#: nova/compute/manager.py:6286
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6336
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but"
" still present on host."
msgstr ""

#: nova/compute/manager.py:6354
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6402
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6412
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr ""

#: nova/compute/manager.py:6475
#, python-format
msgid ""
"Neutron deleted interface %(intf)s; detaching it from the instance and "
"deleting it from the info cache"
msgstr ""

#: nova/compute/manager.py:6510
#, python-format
msgid "Failed to process external instance event %(event)s due to: %(error)s"
msgstr ""

#: nova/compute/resource_tracker.py:418
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:468
#, python-format
msgid "Auditing locally available compute resources for node %(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:475
msgid ""
"Virt driver does not support 'get_available_resource'. Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:555
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:622
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:631
#, python-format
msgid ""
"Final resource view: name=%(node)s phys_ram=%(phys_ram)sMB "
"used_ram=%(used_ram)sMB phys_disk=%(phys_disk)sGB "
"used_disk=%(used_disk)sGB total_vcpus=%(total_vcpus)s "
"used_vcpus=%(used_vcpus)s pci_stats=%(pci_stats)s"
msgstr ""

#: nova/compute/resource_tracker.py:717
#, python-format
msgid "Updating from migration %s"
msgstr ""

#: nova/compute/rpcapi.py:365
#, python-format
msgid ""
"Automatically selected compute RPC version %(rpc)s from minimum service "
"version %(service)i"
msgstr ""

#: nova/conductor/api.py:182
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/consoleauth/manager.py:105
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:130
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:3506
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:5353
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must "
"have been rebooted or crashed. Updating totals."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:36
msgid ""
"Skipped adding instances_project_id_deleted_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:40
#: nova/db/sqlalchemy/migrate_repo/versions/295_add_virtual_interfaces_uuid_index.py:40
#, python-format
msgid "Skipped adding %s because an equivalent index already exists."
msgstr ""

#: nova/image/glance.py:399
#, python-format
msgid "Successfully transferred using %s"
msgstr ""

#: nova/image/s3.py:386
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:163
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:225 nova/network/neutronv2/api.py:1176
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr ""

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr ""

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:336
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:511
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:574
#, python-format
msgid "Network deallocated for instance (fixed IPs: '%s')"
msgstr ""

#: nova/network/manager.py:1037
#, python-format
msgid "Unable to release %s because vif doesn't exist"
msgstr ""

#: nova/network/manager.py:1044
#, python-format
msgid "Unable to release %s because vif object doesn't exist"
msgstr ""

#: nova/network/manager.py:1138
#, python-format
msgid ""
"Ignoring request to release fixed IP %(address)s with MAC %(mac)s since "
"it is now associated with a new instance that is in the process of "
"allocating it's network."
msgstr ""

#: nova/network/minidns.py:193
#, python-format
msgid "deleted %s"
msgstr ""

#: nova/network/neutronv2/api.py:1664
#, python-format
msgid ""
"Port %s from network info_cache is no longer associated with instance in "
"Neutron. Removing from network info_cache."
msgstr ""

#: nova/network/security_group/neutron_driver.py:479
#: nova/network/security_group/neutron_driver.py:534
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr ""

#: nova/scheduler/host_manager.py:468
#, python-format
msgid "Host filter ignoring hosts: %s"
msgstr ""

#: nova/scheduler/host_manager.py:479
#, python-format
msgid "Host filter forcing available hosts to %s"
msgstr ""

#: nova/scheduler/host_manager.py:482
#, python-format
msgid "No hosts matched due to not matching 'force_hosts' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:495
#, python-format
msgid "Host filter forcing available nodes to %s"
msgstr ""

#: nova/scheduler/host_manager.py:498
#, python-format
msgid "No nodes matched due to not matching 'force_nodes' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:580
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""

#: nova/scheduler/host_manager.py:646
#, python-format
msgid "Received an update from an unknown host '%s'. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:664
#, python-format
msgid ""
"Received a delete update from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:682
#, python-format
msgid ""
"The instance sync for host '%s' did not match. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:686
#, python-format
msgid "Successfully synced instances from host '%s'."
msgstr ""

#: nova/scheduler/host_manager.py:690
#, python-format
msgid ""
"Received a sync request from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/filters/utils.py:64
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""

#: nova/scheduler/filters/utils.py:68
#, python-format
msgid "%(num_values)d values found, of which the maximum value will be used."
msgstr ""

#: nova/servicegroup/drivers/db.py:94
msgid "Recovered from being unable to report status."
msgstr ""

#: nova/servicegroup/drivers/mc.py:87
msgid "Recovered connection to memcache server for reporting service status."
msgstr ""

#: nova/virt/block_device.py:248
#, python-format
msgid "preserve multipath_id %s"
msgstr ""

#: nova/virt/block_device.py:494
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/block_device.py:500
#, python-format
msgid "Booting with volume snapshot %(snapshot_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/block_device.py:506
#, python-format
msgid "Booting with volume-backed-image %(image_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/block_device.py:512
#, python-format
msgid "Booting with blank volume at %(mountpoint)s"
msgstr ""

#: nova/virt/driver.py:1627
#, python-format
msgid "Loading compute driver '%s'"
msgstr ""

#: nova/virt/firewall.py:165 nova/virt/libvirt/firewall.py:363
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/firewall.py:425
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr ""

#: nova/virt/disk/mount/api.py:167
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr ""

#: nova/virt/disk/mount/loop.py:35
#, python-format
msgid "Loop mount error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:92 nova/virt/disk/mount/nbd.py:105
#, python-format
msgid "NBD mount error: %s"
msgstr ""

#: nova/virt/disk/vfs/api.py:72
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/vmops.py:257
msgid "Spawning new instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:374 nova/virt/vmwareapi/vmops.py:812
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:388 nova/virt/libvirt/driver.py:2983
#, python-format
msgid "Creating config drive at %(path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:438
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:495
msgid "Soft shutdown succeeded."
msgstr ""

#: nova/virt/ironic/driver.py:766
#, python-format
msgid "Config drive for instance %(instance)s on baremetal node %(node)s created."
msgstr ""

#: nova/virt/ironic/driver.py:790
#, python-format
msgid "Successfully provisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:884
#, python-format
msgid "Successfully unprovisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:916
#, python-format
msgid "Successfully rebooted Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:941
#, python-format
msgid "Successfully powered off Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:967
#, python-format
msgid "Successfully powered on Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:1163
msgid "Instance was successfully rebuilt"
msgstr ""

#: nova/virt/libvirt/driver.py:556
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:803
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:808
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:818
msgid "Instance may be started again."
msgstr ""

#: nova/virt/libvirt/driver.py:828
msgid "Going to destroy instance again."
msgstr ""

#: nova/virt/libvirt/driver.py:1438
msgid "Beginning live snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1441
msgid "Beginning cold snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1472
msgid "Snapshot extracted, beginning image upload"
msgstr ""

#: nova/virt/libvirt/driver.py:1484
msgid "Snapshot image upload complete"
msgstr ""

#: nova/virt/libvirt/driver.py:2111
msgid "Instance soft rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2156
msgid "Instance shutdown successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2164
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr ""

#: nova/virt/libvirt/driver.py:2227
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2267
msgid "Instance already shutdown."
msgstr ""

#: nova/virt/libvirt/driver.py:2282
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2311
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2497
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2513
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: nova/virt/libvirt/driver.py:2549
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2560 nova/virt/libvirt/driver.py:2587
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr ""

#: nova/virt/libvirt/driver.py:2847
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/driver.py:2974
msgid "Using config drive"
msgstr ""

#: nova/virt/libvirt/driver.py:3804
msgid "Configuring timezone for windows instance to localtime"
msgstr ""

#: nova/virt/libvirt/driver.py:5005
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. "
"Instance=%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5012
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats "
"for device"
msgstr ""

#: nova/virt/libvirt/driver.py:5353
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5920
#, python-format
msgid "Error %(ex)s, migration failed"
msgstr ""

#: nova/virt/libvirt/driver.py:5973
#, python-format
msgid "Increasing downtime to %(downtime)d ms after %(waittime)d sec elapsed time"
msgstr ""

#: nova/virt/libvirt/driver.py:6015
#, python-format
msgid ""
"Migration running for %(secs)d secs, memory %(remaining)d%% remaining; "
"(bytes processed=%(processed_memory)d, remaining=%(remaining_memory)d, "
"total=%(total_memory)d)"
msgstr ""

#: nova/virt/libvirt/driver.py:6025
#, python-format
msgid ""
"Data remaining %(remaining)d bytes, low watermark %(watermark)d bytes "
"%(last)d seconds ago"
msgstr ""

#: nova/virt/libvirt/driver.py:6035
msgid "Migration operation has completed"
msgstr ""

#: nova/virt/libvirt/driver.py:6807
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:7190
#, python-format
msgid "Deleting instance files %s"
msgstr ""

#: nova/virt/libvirt/driver.py:7203
#, python-format
msgid "Deletion of %s failed"
msgstr ""

#: nova/virt/libvirt/driver.py:7207
#, python-format
msgid "Deletion of %s complete"
msgstr ""

#: nova/virt/libvirt/firewall.py:117
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:125
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:289
#, python-format
msgid "Failed to undefine network filter %(name)s. Try %(cnt)d of %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/host.py:730
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: "
"%(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:780
#, python-format
msgid "Libvirt host capabilities %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:444
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:192
#, python-format
msgid "Writing stored info to %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:415
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash "
"stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:424
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr ""

#: nova/virt/libvirt/imagecache.py:453
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:456
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:506
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:529
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""

#: nova/virt/libvirt/imagecache.py:612
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:615
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:619
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:150
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:498
msgid "findmnt tool is not installed"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:67
#, python-format
msgid "Mounted volume: %s"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:135
#, python-format
msgid "Fixing previous mount %s which was not unmounted correctly."
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:157
#, python-format
msgid "Trying to disconnected unmounted volume at %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:197
#, python-format
msgid "VMware vCenter version: %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:272
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:290
#, python-format
msgid "Copied virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:304
#, python-format
msgid "Deleted virtual disk %s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:380
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:383 nova/virt/vmwareapi/images.py:449
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/images.py:444
#, python-format
msgid "Downloaded OVA image file %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1333
msgid "Destroyed the VM"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1595
#, python-format
msgid "Created folder: %(name)s in parent %(parent)s."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:919
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1452 nova/virt/xenapi/vmops.py:1701
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1456 nova/virt/xenapi/vmops.py:1705
msgid "Automatically hard rebooting"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:464
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate "
"backing disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/host.py:76
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skip ping migration to a new host"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:397
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:400
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt "
"%(num_attempt)d/%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:687
#, python-format
msgid "Deleted %s snapshots."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1330
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2173
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2469
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2478
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1287
msgid "Starting halted instance found during reboot"
msgstr ""

#: nova/virt/xenapi/vmops.py:1491
msgid "Destroying VM"
msgstr ""

#: nova/virt/xenapi/volumeops.py:65
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:131
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:153
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: nova/vnc/xvp_proxy.py:97
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:103
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:118
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:138
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:141
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:151
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:158
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:178
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/encryptors/luks.py:109
#, python-format
msgid "%s is not a valid LUKS device; formatting device for first use"
msgstr ""

